-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 15:17:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maxi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maxi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maxi` DEFAULT CHARACTER SET utf8 ;
USE `maxi` ;

-- -----------------------------------------------------
-- Table `maxi`.`pendingReservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maxi`.`pendingReservations` (
  `reservationId` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `notes` VARCHAR(100) NULL,
  `tableId` INT NOT NULL,
  PRIMARY KEY (`reservationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maxi`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maxi`.`reservations` (
  `reservationId` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `notes` VARCHAR(100) NULL,
  `tableId` INT NOT NULL,
  PRIMARY KEY (`reservationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maxi`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maxi`.`credentials` (
  `userId` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `type` ENUM('USER', 'ADMIN') NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `maxi`.`pendingReservations`
-- -----------------------------------------------------
START TRANSACTION;
USE `maxi`;
INSERT INTO `maxi`.`pendingReservations` (`reservationId`, `time`, `name`, `notes`, `tableId`) VALUES (1, '2020/10/10 10:10:10.10', 'Georgi', '-', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `maxi`.`reservations`
-- -----------------------------------------------------
START TRANSACTION;
USE `maxi`;
INSERT INTO `maxi`.`reservations` (`reservationId`, `time`, `name`, `notes`, `tableId`) VALUES (1, '2008-11-11 13:23:44', 'Alex', '-', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `maxi`.`credentials`
-- -----------------------------------------------------
START TRANSACTION;
USE `maxi`;
INSERT INTO `maxi`.`credentials` (`userId`, `name`, `email`, `password`, `type`) VALUES (1, 'root', 'root@mail.com', '', 'ADMIN');
INSERT INTO `maxi`.`credentials` (`userId`, `name`, `email`, `password`, `type`) VALUES (2, 'user', 'user@mail.com', '', 'USER');

COMMIT;

